### ISSUE TITLE
Dialyzer type issue with prepared queries

### ISSUE THREAD

**Issue by gornik** [rpt/erlcql#24]
The type for values when executing a query is:

``` erlang
-type values() :: [binary() | {option(), type()}].
```

https://github.com/rpt/erlcql/blob/master/include/erlcql.hrl#L188

But when you prepare a query first and then provide the values, the values need to have type as indicated by Cassandra when preparing a query. E.g. when calling prepare for:

```
SELECT ... LIMIT ?
```

erlcql requires the parameter to be an integer, but that's not what the `values()` type indicate, resulting in dialyzer errors.

I think the easiest fix would be to change typing to:

``` erlang
-type values() :: [type() | {option(), type()}].
```

**Comment by aerosol** [comment]
:+1:

**Comment by rpt** [comment]
Thanks, I will change that.
